keyberon firmware (#3)
* (wip) keyberon firmware

* credentials

* Updated `.gitignore` file.

* credentials

* Fixed compilation errors related to usb.

* wip: switch to the latest rp2040_hal API

* 12*4 => 8*6 grid

* low-hanging fruits (warnings)

* proper type casting for gpio pins

* proper build target

* basic keyboard layout

* Fixed linking error: necessary features on crate `rp2040-hal`.

* Fixed firmware upload script.

* RP2040 chip is now recognised as a USB peripheral.

* Cleanup

* Usb stuck in `Suspend` mode, pls help.

* Firmware very close to Keymini’s but no key presses ar ever detected.

* comment nitpicks

* Wip (matrix).

* transpose the Keyberon matrix

* add a QuackenZero-specific matrix

* fixes: proper pin refs + 1 microsecond delay

* proper configuration

* drop unused rp2040-hal features

* nitpick

* oops, forgot the README

* Swapped `cortex-m-rtic` for `rtic`, due to sub-dependencies issues.

`cortex-m-rtic` depends on `heapless-0.7.7`, which in turn depends
on `atomic-polyfill-1.0.0`, a deprecated crate that just **doesn’t**
compile on my machine, and shouldn’t even be used in the first place.

Swappinging it out for `rtic` solves this issue without affecting
how the keyboard’s work at run-time.

* oops

* a bit of doc

* Switching to 2024 (stable).

The recent switch to rtic[thumbv6] broke the build on my box.
Upgrading to edition2024 and the latest stable Cargo seems to fix it.

---------

Co-authored-by: Nuclear Squid <leo@cazenave.cc>